cwasser_book_shop_api_v1_books:
  type: rest
  resource: "@CwasserBookShopBundle/Controller/BookController.php"
  prefix: /v1

cwasser_book_shop_cart_order_books:
  path: /cart
  defaults: { _controller: CwasserBookShopBundle:Cart:order}
  methods: [POST]
  requirements:
    _format: json|xml
